### ISSUE TITLE
Crash after running for a long time

### ISSUE THREAD

**Issue by NeuroWinter** [Mechazawa/RedBetter-WM2#2]
I keep getting this when I run this for a while:

Grabbing better list                                                      
Traceback (most recent call last):                                        
  File "./redbetter-wm2", line 147, in <module>                           
    main()                                                                
  File "./redbetter-wm2", line 79, in main                                
    torrents = api.get_better(args.better, tags_included)                 
  File "/home/neuro/scripts/RedBetter-WM2/redapi.py", line 245, in get_bet
ter                                                                       
    return self.request('better', method='transcode', type=search_type, se
arch=' '.join(tags))                                                      
  File "/home/neuro/scripts/RedBetter-WM2/redapi.py", line 139, in request
    raise RequestException                                                
redapi.RequestException

**Comment by Mechazawa** [comment]
looks like the api returned some unexpected data. not really something I can account for.
